// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: group.sql

package sqlc

import (
	"context"
)

const createGroup = `-- name: CreateGroup :execlastid
INSERT INTO task_groups (user_id, name, color) VALUES (?, ?, ?)
`

type CreateGroupParams struct {
	UserID int64  `json:"user_id"`
	Name   string `json:"name"`
	Color  string `json:"color"`
}

func (q *Queries) CreateGroup(ctx context.Context, arg CreateGroupParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, createGroup, arg.UserID, arg.Name, arg.Color)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const deleteGroup = `-- name: DeleteGroup :exec
DELETE FROM task_groups WHERE id = ? AND user_id = ?
`

type DeleteGroupParams struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) DeleteGroup(ctx context.Context, arg DeleteGroupParams) error {
	_, err := q.db.ExecContext(ctx, deleteGroup, arg.ID, arg.UserID)
	return err
}

const getGroupByID = `-- name: GetGroupByID :one
SELECT id, user_id, name, color, created_at, updated_at FROM task_groups WHERE id = ? AND user_id = ? LIMIT 1
`

type GetGroupByIDParams struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) GetGroupByID(ctx context.Context, arg GetGroupByIDParams) (TaskGroup, error) {
	row := q.db.QueryRowContext(ctx, getGroupByID, arg.ID, arg.UserID)
	var i TaskGroup
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Color,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listGroupsByUser = `-- name: ListGroupsByUser :many
SELECT id, user_id, name, color, created_at, updated_at FROM task_groups WHERE user_id = ? ORDER BY name ASC
`

func (q *Queries) ListGroupsByUser(ctx context.Context, userID int64) ([]TaskGroup, error) {
	rows, err := q.db.QueryContext(ctx, listGroupsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TaskGroup
	for rows.Next() {
		var i TaskGroup
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Color,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateGroup = `-- name: UpdateGroup :exec
UPDATE task_groups SET name = ?, color = ? WHERE id = ? AND user_id = ?
`

type UpdateGroupParams struct {
	Name   string `json:"name"`
	Color  string `json:"color"`
	ID     int64  `json:"id"`
	UserID int64  `json:"user_id"`
}

func (q *Queries) UpdateGroup(ctx context.Context, arg UpdateGroupParams) error {
	_, err := q.db.ExecContext(ctx, updateGroup,
		arg.Name,
		arg.Color,
		arg.ID,
		arg.UserID,
	)
	return err
}
