// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"database/sql"
	"database/sql/driver"
	"fmt"
	"time"
)

type TasksPriority string

const (
	TasksPriorityLow    TasksPriority = "low"
	TasksPriorityMedium TasksPriority = "medium"
	TasksPriorityHigh   TasksPriority = "high"
)

func (e *TasksPriority) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TasksPriority(s)
	case string:
		*e = TasksPriority(s)
	default:
		return fmt.Errorf("unsupported scan type for TasksPriority: %T", src)
	}
	return nil
}

type NullTasksPriority struct {
	TasksPriority TasksPriority `json:"tasks_priority"`
	Valid         bool          `json:"valid"` // Valid is true if TasksPriority is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTasksPriority) Scan(value interface{}) error {
	if value == nil {
		ns.TasksPriority, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TasksPriority.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTasksPriority) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TasksPriority), nil
}

type TasksStatus string

const (
	TasksStatusPending   TasksStatus = "pending"
	TasksStatusCompleted TasksStatus = "completed"
)

func (e *TasksStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TasksStatus(s)
	case string:
		*e = TasksStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for TasksStatus: %T", src)
	}
	return nil
}

type NullTasksStatus struct {
	TasksStatus TasksStatus `json:"tasks_status"`
	Valid       bool        `json:"valid"` // Valid is true if TasksStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTasksStatus) Scan(value interface{}) error {
	if value == nil {
		ns.TasksStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TasksStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTasksStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TasksStatus), nil
}

type Reminder struct {
	ID        int64          `json:"id"`
	UserID    int64          `json:"user_id"`
	TaskID    int64          `json:"task_id"`
	RemindAt  time.Time      `json:"remind_at"`
	Message   sql.NullString `json:"message"`
	Sent      bool           `json:"sent"`
	CreatedAt time.Time      `json:"created_at"`
	UpdatedAt time.Time      `json:"updated_at"`
}

type Task struct {
	ID          int64          `json:"id"`
	UserID      int64          `json:"user_id"`
	GroupID     sql.NullInt64  `json:"group_id"`
	Title       string         `json:"title"`
	Description sql.NullString `json:"description"`
	Status      TasksStatus    `json:"status"`
	Priority    TasksPriority  `json:"priority"`
	DueAt       sql.NullTime   `json:"due_at"`
	CompletedAt sql.NullTime   `json:"completed_at"`
	CreatedAt   time.Time      `json:"created_at"`
	UpdatedAt   time.Time      `json:"updated_at"`
}

type TaskGroup struct {
	ID        int64     `json:"id"`
	UserID    int64     `json:"user_id"`
	Name      string    `json:"name"`
	Color     string    `json:"color"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type User struct {
	ID           int64     `json:"id"`
	Name         string    `json:"name"`
	Email        string    `json:"email"`
	PasswordHash string    `json:"password_hash"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
}
