// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reminder.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"
)

const createReminder = `-- name: CreateReminder :execlastid
INSERT INTO reminders (user_id, task_id, remind_at, message) VALUES (?, ?, ?, ?)
`

type CreateReminderParams struct {
	UserID   int64          `json:"user_id"`
	TaskID   int64          `json:"task_id"`
	RemindAt time.Time      `json:"remind_at"`
	Message  sql.NullString `json:"message"`
}

func (q *Queries) CreateReminder(ctx context.Context, arg CreateReminderParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, createReminder,
		arg.UserID,
		arg.TaskID,
		arg.RemindAt,
		arg.Message,
	)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const deleteReminder = `-- name: DeleteReminder :exec
DELETE FROM reminders WHERE id = ? AND user_id = ?
`

type DeleteReminderParams struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) DeleteReminder(ctx context.Context, arg DeleteReminderParams) error {
	_, err := q.db.ExecContext(ctx, deleteReminder, arg.ID, arg.UserID)
	return err
}

const listDueReminders = `-- name: ListDueReminders :many
SELECT id, user_id, task_id, remind_at, message, sent, created_at, updated_at FROM reminders WHERE sent = FALSE AND remind_at <= ? ORDER BY remind_at ASC LIMIT ?
`

type ListDueRemindersParams struct {
	RemindAt time.Time `json:"remind_at"`
	Limit    int32     `json:"limit"`
}

func (q *Queries) ListDueReminders(ctx context.Context, arg ListDueRemindersParams) ([]Reminder, error) {
	rows, err := q.db.QueryContext(ctx, listDueReminders, arg.RemindAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Reminder
	for rows.Next() {
		var i Reminder
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.TaskID,
			&i.RemindAt,
			&i.Message,
			&i.Sent,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRemindersByUser = `-- name: ListRemindersByUser :many
SELECT id, user_id, task_id, remind_at, message, sent, created_at, updated_at FROM reminders WHERE user_id = ? ORDER BY remind_at ASC
`

func (q *Queries) ListRemindersByUser(ctx context.Context, userID int64) ([]Reminder, error) {
	rows, err := q.db.QueryContext(ctx, listRemindersByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Reminder
	for rows.Next() {
		var i Reminder
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.TaskID,
			&i.RemindAt,
			&i.Message,
			&i.Sent,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markReminderSent = `-- name: MarkReminderSent :exec
UPDATE reminders SET sent = TRUE WHERE id = ?
`

func (q *Queries) MarkReminderSent(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, markReminderSent, id)
	return err
}
