// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	dto "todo-app/backend/internal/controller/dto"

	mock "github.com/stretchr/testify/mock"

	model "todo-app/backend/internal/model"
)

// GroupServiceInterface is an autogenerated mock type for the GroupServiceInterface type
type GroupServiceInterface struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, userID, req
func (_m *GroupServiceInterface) Create(ctx context.Context, userID int64, req dto.GroupRequest) (model.GroupDTO, error) {
	ret := _m.Called(ctx, userID, req)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 model.GroupDTO
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, dto.GroupRequest) (model.GroupDTO, error)); ok {
		return rf(ctx, userID, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, dto.GroupRequest) model.GroupDTO); ok {
		r0 = rf(ctx, userID, req)
	} else {
		r0 = ret.Get(0).(model.GroupDTO)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, dto.GroupRequest) error); ok {
		r1 = rf(ctx, userID, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: ctx, userID, id
func (_m *GroupServiceInterface) Delete(ctx context.Context, userID int64, id int64) error {
	ret := _m.Called(ctx, userID, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64) error); ok {
		r0 = rf(ctx, userID, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// List provides a mock function with given fields: ctx, userID
func (_m *GroupServiceInterface) List(ctx context.Context, userID int64) ([]model.GroupDTO, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []model.GroupDTO
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) ([]model.GroupDTO, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) []model.GroupDTO); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.GroupDTO)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Share provides a mock function with given fields: ctx, userID, id, req
func (_m *GroupServiceInterface) Share(ctx context.Context, userID int64, id int64, req dto.ShareGroupRequest) error {
	ret := _m.Called(ctx, userID, id, req)

	if len(ret) == 0 {
		panic("no return value specified for Share")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64, dto.ShareGroupRequest) error); ok {
		r0 = rf(ctx, userID, id, req)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Update provides a mock function with given fields: ctx, userID, id, req
func (_m *GroupServiceInterface) Update(ctx context.Context, userID int64, id int64, req dto.GroupRequest) error {
	ret := _m.Called(ctx, userID, id, req)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64, dto.GroupRequest) error); ok {
		r0 = rf(ctx, userID, id, req)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewGroupServiceInterface creates a new instance of GroupServiceInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewGroupServiceInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *GroupServiceInterface {
	mock := &GroupServiceInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
