// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	dto "todo-app/backend/internal/controller/dto"

	mock "github.com/stretchr/testify/mock"

	model "todo-app/backend/internal/model"
)

// ReminderServiceInterface is an autogenerated mock type for the ReminderServiceInterface type
type ReminderServiceInterface struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, userID, req
func (_m *ReminderServiceInterface) Create(ctx context.Context, userID int64, req dto.ReminderRequest) (model.ReminderDTO, error) {
	ret := _m.Called(ctx, userID, req)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 model.ReminderDTO
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, dto.ReminderRequest) (model.ReminderDTO, error)); ok {
		return rf(ctx, userID, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, dto.ReminderRequest) model.ReminderDTO); ok {
		r0 = rf(ctx, userID, req)
	} else {
		r0 = ret.Get(0).(model.ReminderDTO)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, dto.ReminderRequest) error); ok {
		r1 = rf(ctx, userID, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: ctx, userID, id
func (_m *ReminderServiceInterface) Delete(ctx context.Context, userID int64, id int64) error {
	ret := _m.Called(ctx, userID, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64) error); ok {
		r0 = rf(ctx, userID, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// List provides a mock function with given fields: ctx, userID
func (_m *ReminderServiceInterface) List(ctx context.Context, userID int64) ([]model.ReminderDTO, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []model.ReminderDTO
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) ([]model.ReminderDTO, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) []model.ReminderDTO); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.ReminderDTO)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewReminderServiceInterface creates a new instance of ReminderServiceInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewReminderServiceInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *ReminderServiceInterface {
	mock := &ReminderServiceInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
