// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	sqlc "todo-app/backend/internal/db/sqlc"
)

// ReminderRepository is an autogenerated mock type for the ReminderRepository type
type ReminderRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, arg
func (_m *ReminderRepository) Create(ctx context.Context, arg sqlc.CreateReminderParams) (int64, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, sqlc.CreateReminderParams) (int64, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, sqlc.CreateReminderParams) int64); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, sqlc.CreateReminderParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: ctx, arg
func (_m *ReminderRepository) Delete(ctx context.Context, arg sqlc.DeleteReminderParams) error {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, sqlc.DeleteReminderParams) error); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Due provides a mock function with given fields: ctx, arg
func (_m *ReminderRepository) Due(ctx context.Context, arg sqlc.ListDueRemindersParams) ([]sqlc.Reminder, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for Due")
	}

	var r0 []sqlc.Reminder
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, sqlc.ListDueRemindersParams) ([]sqlc.Reminder, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, sqlc.ListDueRemindersParams) []sqlc.Reminder); ok {
		r0 = rf(ctx, arg)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]sqlc.Reminder)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, sqlc.ListDueRemindersParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// List provides a mock function with given fields: ctx, userID
func (_m *ReminderRepository) List(ctx context.Context, userID int64) ([]sqlc.Reminder, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []sqlc.Reminder
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) ([]sqlc.Reminder, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) []sqlc.Reminder); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]sqlc.Reminder)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MarkSent provides a mock function with given fields: ctx, id
func (_m *ReminderRepository) MarkSent(ctx context.Context, id int64) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for MarkSent")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewReminderRepository creates a new instance of ReminderRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewReminderRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *ReminderRepository {
	mock := &ReminderRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
