// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	sqlc "todo-app/backend/internal/db/sqlc"
)

// TaskRepository is an autogenerated mock type for the TaskRepository type
type TaskRepository struct {
	mock.Mock
}

// Count provides a mock function with given fields: ctx, arg
func (_m *TaskRepository) Count(ctx context.Context, arg sqlc.CountTasksByUserParams) (int64, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for Count")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, sqlc.CountTasksByUserParams) (int64, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, sqlc.CountTasksByUserParams) int64); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, sqlc.CountTasksByUserParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Create provides a mock function with given fields: ctx, arg
func (_m *TaskRepository) Create(ctx context.Context, arg sqlc.CreateTaskParams) (int64, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, sqlc.CreateTaskParams) (int64, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, sqlc.CreateTaskParams) int64); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, sqlc.CreateTaskParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: ctx, arg
func (_m *TaskRepository) Delete(ctx context.Context, arg sqlc.DeleteTaskParams) error {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, sqlc.DeleteTaskParams) error); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Get provides a mock function with given fields: ctx, arg
func (_m *TaskRepository) Get(ctx context.Context, arg sqlc.GetTaskByIDParams) (sqlc.Task, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 sqlc.Task
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, sqlc.GetTaskByIDParams) (sqlc.Task, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, sqlc.GetTaskByIDParams) sqlc.Task); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(sqlc.Task)
	}

	if rf, ok := ret.Get(1).(func(context.Context, sqlc.GetTaskByIDParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAccessibleGroup provides a mock function with given fields: ctx, arg
func (_m *TaskRepository) GetAccessibleGroup(ctx context.Context, arg sqlc.GetAccessibleGroupByIDParams) (sqlc.AccessibleGroup, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for GetAccessibleGroup")
	}

	var r0 sqlc.AccessibleGroup
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, sqlc.GetAccessibleGroupByIDParams) (sqlc.AccessibleGroup, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, sqlc.GetAccessibleGroupByIDParams) sqlc.AccessibleGroup); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(sqlc.AccessibleGroup)
	}

	if rf, ok := ret.Get(1).(func(context.Context, sqlc.GetAccessibleGroupByIDParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// List provides a mock function with given fields: ctx, arg
func (_m *TaskRepository) List(ctx context.Context, arg sqlc.ListTasksByUserParams) ([]sqlc.Task, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []sqlc.Task
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, sqlc.ListTasksByUserParams) ([]sqlc.Task, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, sqlc.ListTasksByUserParams) []sqlc.Task); ok {
		r0 = rf(ctx, arg)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]sqlc.Task)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, sqlc.ListTasksByUserParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: ctx, arg
func (_m *TaskRepository) Update(ctx context.Context, arg sqlc.UpdateTaskParams) error {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, sqlc.UpdateTaskParams) error); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewTaskRepository creates a new instance of TaskRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTaskRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *TaskRepository {
	mock := &TaskRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
