// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	dto "todo-app/backend/internal/controller/dto"

	mock "github.com/stretchr/testify/mock"

	model "todo-app/backend/internal/model"
)

// TaskServiceInterface is an autogenerated mock type for the TaskServiceInterface type
type TaskServiceInterface struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, userID, req
func (_m *TaskServiceInterface) Create(ctx context.Context, userID int64, req dto.TaskRequest) (model.TaskDTO, error) {
	ret := _m.Called(ctx, userID, req)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 model.TaskDTO
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, dto.TaskRequest) (model.TaskDTO, error)); ok {
		return rf(ctx, userID, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, dto.TaskRequest) model.TaskDTO); ok {
		r0 = rf(ctx, userID, req)
	} else {
		r0 = ret.Get(0).(model.TaskDTO)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, dto.TaskRequest) error); ok {
		r1 = rf(ctx, userID, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: ctx, userID, id
func (_m *TaskServiceInterface) Delete(ctx context.Context, userID int64, id int64) error {
	ret := _m.Called(ctx, userID, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64) error); ok {
		r0 = rf(ctx, userID, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// List provides a mock function with given fields: ctx, userID, status, groupID, ungrouped, limit, offset, sortBy, sortOrder
func (_m *TaskServiceInterface) List(ctx context.Context, userID int64, status string, groupID int64, ungrouped bool, limit int32, offset int32, sortBy string, sortOrder string) (dto.TaskListResponse, error) {
	ret := _m.Called(ctx, userID, status, groupID, ungrouped, limit, offset, sortBy, sortOrder)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 dto.TaskListResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, string, int64, bool, int32, int32, string, string) (dto.TaskListResponse, error)); ok {
		return rf(ctx, userID, status, groupID, ungrouped, limit, offset, sortBy, sortOrder)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, string, int64, bool, int32, int32, string, string) dto.TaskListResponse); ok {
		r0 = rf(ctx, userID, status, groupID, ungrouped, limit, offset, sortBy, sortOrder)
	} else {
		r0 = ret.Get(0).(dto.TaskListResponse)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, string, int64, bool, int32, int32, string, string) error); ok {
		r1 = rf(ctx, userID, status, groupID, ungrouped, limit, offset, sortBy, sortOrder)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: ctx, userID, id, req
func (_m *TaskServiceInterface) Update(ctx context.Context, userID int64, id int64, req dto.TaskRequest) (model.TaskDTO, error) {
	ret := _m.Called(ctx, userID, id, req)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 model.TaskDTO
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64, dto.TaskRequest) (model.TaskDTO, error)); ok {
		return rf(ctx, userID, id, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64, dto.TaskRequest) model.TaskDTO); ok {
		r0 = rf(ctx, userID, id, req)
	} else {
		r0 = ret.Get(0).(model.TaskDTO)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, int64, dto.TaskRequest) error); ok {
		r1 = rf(ctx, userID, id, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewTaskServiceInterface creates a new instance of TaskServiceInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTaskServiceInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *TaskServiceInterface {
	mock := &TaskServiceInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
